// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIIDCC8y5LBLAdH5Uz0aetbf7OgU7B64A',
    appId: '1:902833889363:web:6325946a0d1856885226a6',
    messagingSenderId: '902833889363',
    projectId: 'warmindo-d1658',
    authDomain: 'warmindo-d1658.firebaseapp.com',
    storageBucket: 'warmindo-d1658.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDClL206s5XKQUBYtTxEE_UXrKRXg8a1Sw',
    appId: '1:902833889363:android:fad9da0885c4ccca5226a6',
    messagingSenderId: '902833889363',
    projectId: 'warmindo-d1658',
    storageBucket: 'warmindo-d1658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXjoaA6E8ZAFtFSKJlKpOclk7OhYV0n3k',
    appId: '1:902833889363:ios:2b7f30ef8a29f2965226a6',
    messagingSenderId: '902833889363',
    projectId: 'warmindo-d1658',
    storageBucket: 'warmindo-d1658.appspot.com',
    iosBundleId: 'com.example.warmindo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXjoaA6E8ZAFtFSKJlKpOclk7OhYV0n3k',
    appId: '1:902833889363:ios:9902515ddcf78b325226a6',
    messagingSenderId: '902833889363',
    projectId: 'warmindo-d1658',
    storageBucket: 'warmindo-d1658.appspot.com',
    iosBundleId: 'com.example.warmindo.RunnerTests',
  );
}
